return {
	"vessels:glass_bottle",
	"pep",
	"pep:speedplus",
	"pep:speedminus",
	"pep:speedreset",
	"pep:breath",
	"pep:regen",
	"pep:regen2",
	"pep:grav0",
	"pep:gravreset",
	"pep:jumpplus",
	"pep:jumpminus",
	"pep:jumpreset",
	"pep:mole",
}