return {
	"default:snow",
	"mesecons_materials:glue",
	"bucket:bucket_empty",
	"bucket:bucket_water",
	"bucket:bucket_river_water",
	"bucket:bucket_lava",

	"mobs_animal:bear",
	"mobs_animal:bunny",
	"mobs_animal:chicken",
	"mobs_animal:cow",
	"mobs_animal:dog",
	"mobs_animal:kitten",
	"mobs_animal:pig",
	"mobs_animal:wolf",
	"mobs_animal:sheep_white",
	"mobs_monster:spider",
	"mobs_monster:small_spider",
	"mobs_monster:skeleton",
	"mobs_monster:zombie",
}